name: Esteira de Desenvolvimento

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Fase 1 - Checkout do Código
        uses: actions/checkout@v4

      - name: Fase 2 - Instalação de Dependências
        run: echo "Instalando dependências..."

      - name: Fase 3 - Build
        run: echo "Executando build do projeto..."

      - name: Fase 4 - Testes
        run: echo "Executando testes automatizados..."

      - name: Fase 5 - Análise de Qualidade
        run: echo "Analisando qualidade do código..."

      - name: Fase 6 - Deploy
        run: echo "Realizando deploy..."
